### ISSUE TITLE
docs (wiki) visibility

### ISSUE THREAD

**Issue by olzama** [delph-in/docs#10]
It's my understanding that the wiki is associated specifically with the docs repo; e.g. there is no link to the wiki that would be organization-wide.

The docs repo itself is not very visible. 

Can we make it more so?

**Comment by olzama** [comment]
Oh! I guess it can just be pinned.

**Comment by goodmami** [comment]
I believe that once the wiki conversion is considered "ready", Stephan was offering to redirect a delph-in.net domain to the new GitHub docs. I think we can also create a `delph-in.github.io` repository with some static HTML as a landing page.

In any case, I've now replaced the `jacy` and `delphin-viz` pins with `matrix` and `docs`.

**Comment by arademaker** [comment]
O just want to say that I consider the migration of the wiki ready!!

We need to formally notify people about it, but all erros we found were fixed or are planned to be fixed in the new wiki. No justification for a new batch process of migration. Moreover, we have already started to make manual adjusts in the new wiki.

**Comment by olzama** [comment]
> We need to formally notify people about it

Yes! But I am waiting for the Participants membership issue to be resolved in some reliable and systematic way though. Right now that group is still empty so if we announce people can edit the wiki, many of them will find that they can't.

**Comment by guyemerson** [comment]
Fantastic news!
