### ISSUE TITLE
MatrixDocTop should be exposed through the delph-in docs site

### ISSUE THREAD

**Issue by emilymbender** [delph-in/docs#137]
@EricZinda apologies but I can't quickly navigate back to where I would edit this myself. Somehow this page:
https://delph-in.github.io/docs/matrix/MatrixDocTop

which corresponds to: 
https://github.com/delph-in/docs/wiki/MatrixDocTop

is a 404 on the docs site. Can you fix it?

**Comment by EricZinda** [comment]
No problem. We moved it during the summit to be part of the How-To section, here: https://delph-in.github.io/docs/howto/MatrixDocTop/. As far as I can tell, all the links properly link to that location.  I'm curious where you found this broken link, or did you just type it in directly because you expected it there?

Here's how I fixed things up:

At the summit I took the action item to figure out how to put wiki pages in multiple places in the docs, and here's the answer: you can put them in as many places as you want in the docs site, but by default any link to them will only go to the *first* one in the site. If you don't want that, you can choose the "definitive" one by setting `"DefinitiveLink": true` so that all links go there.

So, I put the page both in the [How-To section](https://delph-in.github.io/docs/howto/MatrixDocTop/) and the [Grammar Matrix section](https://delph-in.github.io/docs/matrix/MatrixDocTop/) and I set the Grammar Matrix section one as definitive.  

The link should work now, and links will go to the Grammar Matrix section.
