### ISSUE TITLE
The demo delphin viz site is often not fully working

### ISSUE THREAD

**Issue by olzama** [delph-in/docs#41]
I've been relying on this site a lot, particularly to show people the ERG quickly: 

https://delph-in.github.io/delphin-viz/demo/

Currently it's not working: The site itself isn't down but the grammars aren't accessible, I think.

I think it has happened before but I don't remember what the issue was.

Anything that can be done, both short and long term?..

**Comment by emilymbender** [comment]
Does that point to something running at UW, and if so, is there something we need to restart here? Olga, when was the last time it worked for you?

**Comment by olzama** [comment]
I tried the ones pointing to UW and the one pointing to Oslo; none seem to work. I am not entirely sure when the last time was it was working; I think a couple months ago? But I am not sure.

**Comment by goodmami** [comment]
I noticed this the other day but currently it's working for me. Maybe someone fixed it in the meantime?

In the past, restarting the server helped. I think once or twice the disk had filled up and needed to be cleared, but I'm not sure if that's the case this time.

**Comment by emilymbender** [comment]
Is "the server" / what restarting it entails documented anywhere?

**Comment by goodmami** [comment]
@emilymbender no, I don't think it's documented. "The server" is "chimpanzee" I think, and easiest is probably to ask Brandon to restart it, and he should be able to tell if there's anything that needs fixing.

**Comment by emilymbender** [comment]
From Brandon:

What is the connection between  "https://delph-in.github.io/delphin-viz/demo" and chimpanzee? The site seems to be hosted somewhere else, but I don't know what that site is referencing on chimpanzee that is allowing the connection.

The closest thing on chimpanzee I could find that matches that use case is: "http://chimpanzee.ling.washington.edu/demophin/erg/" Which seems to be working(as far as I can tell. I can put in a sentence and hit parse and it produces something.)

**Comment by bmgraves** [comment]
Quick Update I've found whats running on chimpanzee that the https://delph-in.github.io/delphin-viz/demo site is referencing, but I cannot for the life of me figure out where the issue is.

Using Developer tools on the delph-in side, I see that it is communicating with this address: 

http://chimpanzee.ling.washington.edu/bottlenose/erg-2018/parse?derivation=json&mrs=null&dmrs=null&input=this%20is%20a%20test&results=5

However, if you go to that address, it is returning valid json data. That seems to suggest that the issue is on the delph-in side, but it is of course still possible to be an issue on the chimpanzee side.

I'll keep poking things on the chimpanzee side to see what else I can find, but any info from the delph-in side about what that process is would be helpful.

**Comment by goodmami** [comment]
Thanks @bmgraves, and, yes, the demo site is simple HTML and javascript hosted on GitHub, but it calls a JSON API on chimpanzee which is, as you've noticed, the "bottlenose" app.

It's now showing me the error in the browser again, so I can confirm that calling the chimpanzee server directly is not giving an error:

```console
$ curl -I "http://chimpanzee.ling.washington.edu/bottlenose/erg-2018/parse?derivation=json&mrs=null&dmrs=json&input=Abrams%20knew%20that%20it%20rained.&results=5"
HTTP/1.1 200 OK
Date: Tue, 01 Feb 2022 05:53:06 GMT
Server: Apache/2.4.18 (Ubuntu)
Access-Control-Allow-Headers: Authorization, Origin, Accept, Content-Type, X-Requested-With
Access-Control-Allow-Origin: *
Content-Length: 11671
Access-Control-Allow-Methods: GET, POST
Content-Type: application/json
```

But in the browser's developer console I see the following error:

> *Blocked loading mixed active content “http://erg.delph-in.net/rest/0.9/parse?derivation=json&mrs=null&dmrs=json&input=Abrams%20knew%20that%20it%20rained.&results=5”jquery.min.js:4:16837*

This sounds like it's because the page is served via HTTPS but the chimpanzee server is HTTP (hence "mixed content"; also see [this StackOverflow question](https://stackoverflow.com/q/18251128/1441112). Perhaps we're seeing this now because browsers started blocking these by default? I don't know how feasible it is to get chimpanzee an SSL cert so it can serve HTTPS.

**Comment by bmgraves** [comment]
@goodmami thanks for the info! Chimpanzee has been updated with an SSL certificate and reloaded. HTTPS is functional, if the address on the demo site can be updated to reference https instead of http that should either fix it, or at least eliminate it as a factor.

**Comment by goodmami** [comment]
Thanks, but it seems like there are new problems. Trying `curl` with the `http` URL now gives a 404, and with the `https` URL I get this:

> ```
> curl: (60) SSL certificate problem: unable to get local issuer certificate
> More details here: https://curl.se/docs/sslcerts.html
> 
> curl failed to verify the legitimacy of the server and therefore could not
> establish a secure connection to it. To learn more about this situation and
> how to fix it, please visit the web page mentioned above.
> ```

I tried logging into chimpanzee and running `apache2ctl graceful` to restart the server, but I got an error message about a syntax error in one of the conf files. @bmgraves, could you inspect this a bit further?

**Comment by bmgraves** [comment]
Sorry about that. The CA certificate on chimpanzee was out of date so curl requests weren't being authenticated even though direct webrowser requests were working. Should now be working properly.

**Comment by goodmami** [comment]
Ok, I confirm that it now works via curl, and I also pushed updates to the site so it would use the https connection. It works for me now, except for the UiO version, which is still http. Thanks, @bmgraves!

I also created delph-in/delphin-viz#8 (this issue should have been on that repo initially) for further tracking.
